app = "scene-understanding-api"
kill_signal = "SIGINT"
kill_timeout = 5

[build]
  image = "scene-understanding-api:latest"

[http_service]
  internal_port = 7860
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[env]
  MODEL_CACHE_PATH = "/app/models"
  CONFIDENCE_THRESHOLD = "0.5"
  MAX_FRAMES_MEMORY = "10"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
